<div id="myNav" class="overlay">
</div>
<div class="visualizer-wrap">
    <div class="head_tab__list">
        <?php echo $this->getVisualHeader(); ?>
    </div>
    <div class="visual_content">
        <?php echo $this->getVisualContent(); ?>
    </div>
</div>



<!-- <link rel="stylesheet" type="text/css" href="<.?php echo $block->getViewFileUrl('css/visualizer.css') ?>"> -->
<script src="<?php echo $block->getViewFileUrl('js/visualizer.js') ?>">