<div id="myNav" class="overlay">
</div>
<div class="visualizer-wrap">
    <div class="head_tab__list">
        <div class="title-head-tab-list">Sản phẩm</div>
        <div class="head-tab-list-wrap">
            <?php echo $this->getVisualHeader(); ?>
        </div>
        <div class="cus-select-down select-arrow"></div>
    </div>
    <div class="visual_content">
        <?php echo $this->getVisualContent(); ?>
    </div>
</div>



<!-- <link rel="stylesheet" type="text/css" href="<.?php echo $block->getViewFileUrl('css/visualizer.css') ?>"> -->
<script src="<?php echo $block->getViewFileUrl('js/visualizer.js') ?>">