<?php
    $_category_desc = $this->helper('Smartwave\Porto\Helper\Data')->getConfig('porto_settings/category/category_description');
?>
<?php if ($_category_desc == "full_width" && $_description = $block->getCurrentCategory()->getDescription()): ?>
    <style>
        .type12 {
            position: absolute;
            width: 100%;
        }

        .category-custom-description {
            position: absolute;
            top: 13.5%;
            width: 100%;
            background-image: linear-gradient(90deg, rgba(0,0,0,0) 0%, rgba(0,0,0,0.55) 50%, rgba(0,0,0,0) 100%);
            padding-bottom: 4vh;
            padding-top: 4vh;
        }

        .category-custom-description h1 {
            text-align: center;
            border-bottom: solid 3px;
            border-image: linear-gradient(to left, rgba(209, 156, 21, 0) 30%, rgb(208, 179, 105) 50%, rgba(209, 156, 21, 0) 70%) 0 0 100% 0/1px 0 3px 0 stretch;
            color: white;
            padding-bottom: 1vh;
            margin-bottom: 4.5vh;
            font-size: 2vw;
            font-weight: 300;
        }

        .category-custom-description p {
            text-align: center;
            width: 50%;
            margin: auto;
            color: white;
            font-size: 1vw;
            font-weight: 300;
            font-family: 'Josefin Sans', sans-serif;
        }

        .category-description img {
            width: 100%;
        }

        @media (max-width: 575px) {
            .category-custom-description {
                top: 15em;
                padding-bottom: 2em;
                padding-top: 2em;
                font-size: 6px;
            }

            .category-custom-description h1 {
                padding-bottom: 0.5em;
                margin-bottom: 1em;
                font-size: 2em;
            }

            .category-custom-description p {
                width: 80%;
                line-height: 1em;
                font-size: 1.2em;
            }
        }
    </style>
    
    <div class="category-description no-margin">
        <?php echo $this->helper('Magento\Catalog\Helper\Output')->categoryAttribute($block->getCurrentCategory(), $_description, 'description') ?>
    </div>
<?php endif; ?>
