<style>
    .type12 {
        position: absolute;
        width: 100%;
    }

    .category-custom-description {
        position: absolute;
        top: 10%;
        width: 100%;
        background-image: linear-gradient(90deg, rgba(0,0,0,0) 0%, rgba(0,0,0,0.5) 50%, rgba(0,0,0,0) 100%);
        padding-bottom: 4vh;
        padding-top: 4vh;
    }

    .category-custom-description h1 {
        text-align: center;
        border-bottom: solid 3px;
        border-image: linear-gradient(to left, rgba(209, 156, 21, 0) 30%, rgb(208, 179, 105) 50%, rgba(209, 156, 21, 0) 70%) 0 0 100% 0/1px 0 3px 0 stretch;
        color: white;
        padding-bottom: 1vh;
        margin-bottom: 5vh;
        font-size: 1.5vw;
        font-weight: 400;
    }

    .category-custom-description p {
        text-align: center;
        width: 40%;
        margin: auto;
        color: white;
        font-size: 1vw;
        font-weight: 300;
    }

    @media (max-width: 575px) {
        .category-custom-description {
            top: 7%;
            padding-bottom: 2em;
            padding-top: 2em;
        }

        .category-custom-description h1 {
            padding-bottom: 0.5em;
            margin-bottom: 1em;
            font-size: 2em;
        }

        .category-custom-description p {
            width: 80%;
            line-height: 1em;
            font-size: 1.2em;
        }
    }
</style>


<!-- < ?php

    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $storeManager  = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
    $storeID = $storeManager->getStore()->getStoreId();

    $_rootCategoryId = $objectManager->get('Magento\Variable\Model\Variable')->setStoreId($storeID)->loadByCode('root_product_category_id')->getPlainValue(); // Return Plain Value
    $_objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $_rootCategory = $_objectManager->create('Magento\Catalog\Model\Category')
    ->load($_rootCategoryId);

    $_categoryCollection =  $_rootCategory->getChildrenCategories();


    $_description = null;
    $_category = null;
    $product = $block->getProduct(); // Get the current product object
    $categoryCollection = $product->getCategoryCollection(); // Get the collection of categories the product belongs to

    foreach ($categoryCollection as $category) { // Loop through each category
        $category->load($category->getId());
        // if (!empty($category->getDescription())) { // If the description is not empty
        if ($_categoryCollection->contains($category)) { // If the description is not empty
            $_description = $category->getDescription(); // Return the description
            $_category = $category;
            break;
        }
    }
    $_category_desc = $this->helper('Smartwave\Porto\Helper\Data')->getConfig('porto_settings/category/category_description');
    // $_description = $block->getCurrentCategory()->getDescription();

    if ($_description != null): ?>
    <div class="category-description no-margin">
        < ?php echo $this->helper('Magento\Catalog\Helper\Output')->categoryAttribute($_category, $_description, 'description') ?>
    </div>
< ?php endif; ?> -->

<?php
    $_description = null;
    $_category = null;
    try {
        $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
        $storeManager  = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
        $storeID = $storeManager->getStore()->getStoreId();

        $_rootCategoryId = $objectManager->get('Magento\Variable\Model\Variable')->setStoreId($storeID)->loadByCode('root_product_category_id')->getPlainValue(); // Return Plain Value
        $_objectManager = \Magento\Framework\App\ObjectManager::getInstance();
        $_rootCategory = $_objectManager->create('Magento\Catalog\Model\Category')
        ->load($_rootCategoryId);
        $targetCategoryCollection = $_rootCategory->getCollection();
        // $_categoryCollection =  $_rootCategory->getChildrenCategories();

        $product = $block->getProduct(); // Get the current product object
        $_categoryCollection = $product->getCategoryCollection(); // Get the collection of categories the product belongs to
    
        foreach ($_categoryCollection as $category) { // Loop through each category
            foreach ($targetCategoryCollection as $targetCategory) { // Loop through each category in target collection
                $targetCategory->load($targetCategory->getId());
                if ($_rootCategoryId != $targetCategory->getId() && $targetCategory->getId() == $category->getId() && $targetCategory->getDescription()) { // If the category exists and the description is not empty
                    $_description = $targetCategory->getDescription(); // Set the description
                    $_category = $targetCategory; // Set the category
                    break;
                }
            }
        }
        $_category_desc = $this->helper('Smartwave\Porto\Helper\Data')->getConfig('porto_settings/category/category_description');
        // $_description = $block->getCurrentCategory()->getDescription();
    } catch (\Exception $e) {
        echo "Error: " . $e->getMessage();
        // Handle the exception as needed
    }
?>

<?php if ($_description != null): ?>
<div class="category-description no-margin">
    <?php echo $this->helper('Magento\Catalog\Helper\Output')->categoryAttribute($_category, $_description, 'description') ?>
</div>
<?php endif; ?>

