<link rel="stylesheet" type="text/css" href="<?php echo $block->getViewFileUrl('Magento_Catalog::css/banner.css')?>">

<?php
    $_description = null;
    $_category = null;
    try {
        $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
        $storeManager  = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
        $storeID = $storeManager->getStore()->getStoreId();

        $_rootCategoryId = $objectManager->get('Magento\Variable\Model\Variable')->setStoreId($storeID)->loadByCode('root_product_category_id')->getPlainValue(); // Return Plain Value
        $_objectManager = \Magento\Framework\App\ObjectManager::getInstance();
        $_rootCategory = $_objectManager->create('Magento\Catalog\Model\Category')
        ->load($_rootCategoryId);
        $targetCategoryCollection = $_rootCategory->getCollection();
        // $_categoryCollection =  $_rootCategory->getChildrenCategories();

        $product = $block->getProduct(); // Get the current product object
        $_categoryCollection = $product->getCategoryCollection(); // Get the collection of categories the product belongs to
    
        foreach ($_categoryCollection as $category) { // Loop through each category
            foreach ($targetCategoryCollection as $targetCategory) { // Loop through each category in target collection
                $targetCategory->load($targetCategory->getId());
                if ($_rootCategoryId != $targetCategory->getId() && $targetCategory->getId() == $category->getId() && $targetCategory->getDescription()) { // If the category exists and the description is not empty
                    $_description = $targetCategory->getDescription(); // Set the description
                    $_category = $targetCategory; // Set the category
                    break;
                }
            }
        }
        $_category_desc = $this->helper('Smartwave\Porto\Helper\Data')->getConfig('porto_settings/category/category_description');
        // $_description = $block->getCurrentCategory()->getDescription();
    } catch (\Exception $e) {
        echo "Error: " . $e->getMessage();
        // Handle the exception as needed
    }
?>

<?php if ($_description != null): ?>
<div class="category-description no-margin">
    <?php echo $this->helper('Magento\Catalog\Helper\Output')->categoryAttribute($_category, $_description, 'description') ?>
</div>
<?php endif; ?>

