<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$category = $objectManager->get('Magento\Framework\Registry')->registry('current_category'); //Get Current Category
?>
<?php if($category): ?>
<?php 
$subcats = $category->getChildrenCategories();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
    if(count($subcats)>0){
?>
<?php
    }
?>
<?php endif; ?>