<?php
    $_helper = $this->helper('Smartwave\Porto\Helper\Data');
    $header_type = $this->getConfig('porto_settings/header/header_type');
    $header2_text = $this->getConfig('porto_settings/header/header2_text');
    $show_notice = $this->getConfig('porto_settings/general/show_site_notice');
    if ($show_notice && $show_notice == 1)
        echo $this->getChildHtml("porto_custom_notice");
?>

<header class="page-header type<?php echo $header_type; ?>" >
<?php echo $this->getChildHtml("header_customer_form_login"); ?>

<?php
  $store_menu_block = $block->getLayout()->getBlock("sw.topnav");
  $sub_menu_html = $store_menu_block->getSubmenuItemsHtmlById();
?>

<div class="header-main header-top">
  <div class="header content header-row" style="max-width: 100%;">
    <div class="header-left flex-1 hide-in-large-scr">
      <span data-action="toggle-nav" class="action nav-toggle">
        <span><?php echo __('Toggle Nav') ?></span>
      </span>
    </div>

    <div class="header-left nav-sections-left hide-in-small-scr">
      <div class="sections nav-sections">
        <div class="section-items nav-sections-items mage-tabs-disabled" role="tablist">
          <div class="section-item-title nav-sections-item-title active" data-role="collapsible" role="tab" data-collapsible="true" aria-controls="store.menu" aria-selected="false" aria-expanded="true" tabindex="0">
            <a class="nav-sections-item-switch" data-toggle="switch" href="#store.menu"> Menu </a>
          </div>
          <div class="section-item-content nav-sections-item-content" id="store.menu" data-role="content" role="tabpanel" aria-hidden="false">
            <nav class="navigation sw-megamenu" role="navigation">
              <ul>
                <li class="ui-menu-item level0 fullwidth">
                  <a href="/" class="level-top" title="TRANG CHỦ"><span>TRANG CHỦ</span></a>
                </li>
                <li class="ui-menu-item level0 fullwidth">
                  <a href="https://o2sconcept.com/gioi-thieu" class="level-top" title="GIỚI THIỆU"><span>GIỚI THIỆU</span></a>
                </li>
              </ul>
            </nav>
            <script type="text/javascript">
              require(["jquery", "Smartwave_Megamenu/js/sw_megamenu"], function ($) {
                $(".sw-megamenu").swMegamenu();
              });
            </script>
          </div>
        </div>
      </div>
    </div>

    <div class="header-center" style="padding: 10px;"><?php echo $this->getChildHtml("logo"); ?></div>

    <div class="header-right nav-sections-right">
      <?php echo $this->getChildHtml("navigation.sections"); ?>

      <span class="separator"></span>

      <div class="search-area show-icon" style="right: 20px;">
        <a href="javascript:void(0);" class="search-toggle-icon">
          <span><i class="porto-icon-magnifier"></i></span>
        </a>
        <?php echo $this->getChildHtml("top.search"); ?>
      </div>

      <?php echo $this->getChildHtml("minicart"); ?>

      <div class="panel header show-icon">
        <div class="top-links-icon">
          <a href="javascript:;"><i class="porto-icon-user-2"></i></a>
        </div>
        <?php echo $this->getChildHtml("header.links"); ?>
      </div>
    </div>
  </div>
</div>

<div class="header-bottom header-main hide-in-small-scr">
  <nav class="navigation sw-megamenu" role="navigation">
    <?php echo $sub_menu_html; ?>
  </nav>
</div>

</header>

<?php
    if ($show_notice && $show_notice == 2)
        echo $this->getChildHtml("porto_custom_notice");
?>