<?php
    $_helper = $this->helper('Smartwave\Porto\Helper\Cssconfig');
    $porto_helper = $this->helper('Smartwave\Porto\Helper\Data');
    $_redirect_cart = $porto_helper->getConfig('checkout/cart/redirect_to_cart');
?>

<meta http-equiv="Content-Security-Policy" content="frame-ancestors https://www.facebook.com">
<meta http-equiv="X-Frame-Options" content="ALLOW-FROM https://www.facebook.com">
<meta property="og:image" itemprop="thumbnailUrl" content="<?php echo $block->getViewFileUrl('favicon/apple-touch-icon.png'); ?>">
<meta property="og:image:width" content="800">
<meta property="og:image:height" content="354">
<link rel="apple-touch-icon" sizes="180x180" href="<?php echo $block->getViewFileUrl('favicon/apple-touch-icon.png'); ?>">
<link rel="icon" type="image/png" sizes="32x32" href="<?php echo $block->getViewFileUrl('favicon/favicon-32x32.png'); ?>">
<link rel="icon" type="image/png" sizes="16x16" href="<?php echo $block->getViewFileUrl('favicon/favicon-16x16.png'); ?>">
<link rel="manifest" href="<?php echo $block->getViewFileUrl('favicon/site.webmanifest'); ?>">

<?php
    $d = $this->getConfig('porto_design');
    $charSubset = "";
    if (isset($d['font']['char_latin_ext']) && $d['font']['char_latin_ext']==1 ) {
      $charSubset .= ',latin-ext';
    }
    if (isset($d['font']['char_subset']) && $d['font']['char_subset']){
        $charSubset .= ','.$d['font']['char_subset'];
    }
    $font_sizes = "%3A300%2C300italic%2C400%2C400italic%2C600%2C600italic%2C700%2C700italic%2C800%2C800italic"; 
    if (isset($d['font']['custom']) && $d['font']['custom'] && $d['font']['font_family'] == 'google'){
      $font_family = str_replace(' ', '+', $d['font']['google_font_family']).$font_sizes.$charSubset;
    }
?>
<?php if (isset($d['font']['custom']) && $d['font']['custom'] && $d['font']['font_family'] == 'google'){ ?>
<link rel='stylesheet' href='//fonts.googleapis.com/css?family=<?php echo $font_family;?>' type='text/css' />
<?php }else{ ?>
<link rel='stylesheet' href="//fonts.googleapis.com/css?family=Open+Sans%3A300%2C300italic%2C400%2C400italic%2C600%2C600italic%2C700%2C700italic%2C800%2C800italic&amp;v1&amp;subset=latin%2Clatin-ext" type="text/css" media="screen"/>
<?php } ?>
<link href="//fonts.googleapis.com/css?family=Oswald:300,400,500,600,700" rel="stylesheet">
<link href="//fonts.googleapis.com/css?family=Poppins:200,300,400,500,600,700,800" rel="stylesheet">
<link rel="stylesheet" href="//fonts.googleapis.com/css?family=Open+Sans%3A300%2C300italic%2C400%2C400italic%2C600%2C600italic%2C700%2C700italic%2C800%2C800italic&amp;v1&amp;subset=latin%2Clatin-ext" type="text/css" media="screen"/>
<?php if ($this->getConfig('porto_settings/optimization/bootstrap')): ?>
    <link rel="stylesheet" type="text/css" media="all" href="<?php echo $_helper->getPortoWebDir().'bootstrap/css/bootstrap.min.css'; ?>">
<?php else: ?>
    <link rel="stylesheet" type="text/css" media="all" href="<?php echo $_helper->getPortoWebDir().'bootstrap/css/bootstrap.optimized.min.css'; ?>">
<?php endif; ?>
<?php if ($this->getConfig('porto_settings/optimization/animate')): ?>
    <link rel="stylesheet" type="text/css" media="all" href="<?php echo $_helper->getPortoWebDir().'css/animate.css'; ?>">
<?php else: ?>
    <link rel="stylesheet" type="text/css" media="all" href="<?php echo $_helper->getPortoWebDir().'css/animate.optimized.css'; ?>">
<?php endif; ?>
<?php
    $header_type = $this->getConfig('porto_settings/header/header_type');
?>
<link rel="stylesheet" type="text/css" media="all" href="<?php echo $block->getViewFileUrl('css/type12.css'); ?>">
<link rel="stylesheet" type="text/css" media="all" href="<?php echo $block->getViewFileUrl('css/custom.css'); ?>">

<link rel="stylesheet" type="text/css" media="all" href="/media/o2sconcept/css/lity.css">
<link rel="stylesheet" type="text/css" media="all" href="/media/o2sconcept/css/swiper-bundle.min.css">

<script type="text/javascript">
var redirect_cart = false;
<?php if($_redirect_cart):?>
    redirect_cart = true;
<?php endif;?>
var porto_config = {
    paths: {
        'parallax': 'js/jquery.parallax.min',
        'owlcarousel': 'owl.carousel/owl.carousel',
        'floatelement': 'js/jquery.floatelement',
        'lity': 'js/lity'
    },
    shim: {
        'owlcarousel': {
          deps: ['jquery']
        },
        'owlcarousel_thumbs': {
          deps: ['jquery','owlcarousel']
        },
        'floatelement': {
          deps: ['jquery']
        }
    }
};

require.config(porto_config);
</script>

<script type="text/javascript">
  require(["lity"], function(){});
</script>

<script type="text/javascript">
require([
    'jquery'
], function ($) {
<?php if ($this->getConfig('porto_settings/header/sticky_header')): ?>
  $(window).ready(function(){
    var landing_block = document.getElementById("landing_block");

    if (!landing_block) {
      $('.header-bottom').css("display", 'inherit');
    }
  });
  
  var scrolled = false;
    $(window).scroll(function(){
        if($(window).width()>=992){
            var landing_block = document.getElementById("landing_block");

            var threshold_height = 0;
            if (landing_block) {
              threshold_height = landing_block.offsetHeight + threshold_height;
            }

            if(threshold_height<$(window).scrollTop() && !scrolled){
                $('.page-header:not(.sticky-header)').css("height",$('.page-header:not(.sticky-header)').height()+'px');
                $('.page-header').addClass("sticky-header");
                scrolled = true;
                <?php if ($this->getConfig('porto_settings/header/sticky_header_logo')): ?>
                <?php
                if($logo_src = $this->getConfig('porto_settings/header/sticky_header_logo_src')){
                    $folderName = \Smartwave\Porto\Model\Config\Backend\Image\Stickylogo::UPLOAD_DIR;
                    $path = $folderName . '/' . $logo_src;
                    $imageUrl = $porto_helper->getBaseUrl() . $path;
                ?>
                $(".sticky-logo img").attr("src","<?php echo $imageUrl; ?>");
                <?php
                }
                ?>
                <?php endif; ?>

                if (landing_block) {
                  $('.header-bottom').css("display", 'inherit');
                }
            }
            if(threshold_height>=$(window).scrollTop() && scrolled){
                $('.page-header.sticky-header').css("height",'');
                $('.page-header').removeClass("sticky-header");
                scrolled = false;

                if (landing_block) {
                  $('.header-bottom').css("display", 'none');
                }
            }
        }
        if($('body').hasClass('mobile-sticky')) {
            if($(window).width()<=991){
                if(130<$(window).scrollTop() && !scrolled){
                  $('.page-header:not(.sticky-header)').css("height",$('.page-header:not(.sticky-header)').height()+'px');
                  $('.page-header').addClass("sticky-header");
                  scrolled = true;
                }
                if(130>=$(window).scrollTop() && scrolled){
                  $('.page-header.sticky-header').css("height",'auto');
                  $('.page-header').removeClass("sticky-header");
                  scrolled = false;
                }
            }
        }
    });
    $(window).resize(function(){
      var b_w = $(window).width();
      if(b_w <= 991){
        if($('.page-header .navigation .minicart-wrapper').length > 0) {
          var minicart;
          minicart = $('.page-header .navigation .minicart-wrapper').detach();
          $('.minicart-place').after(minicart);
          $('.minicart-place').remove();
          $('.page-header .minicart-wrapper-moved').addClass("minicart-wrapper").removeClass("minicart-wrapper-moved").removeClass("hide");
        }
      }
    });
<?php endif; ?>
});
</script>
<?php if($this->getConfig('porto_settings/general/smartlayers')): ?>
<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-58378513496862c5"></script>
<?php endif; ?>

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Josefin+Sans:ital,wght@0,100;0,300;0,400;0,500;1,100;1,300;1,400;1,500&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;1,100;1,300;1,400;1,500&display=swap" rel="stylesheet">

</style>